services:
  gateway:
    container_name: ninja_portal
    build:
      context: .
      args:
        INSTALL_DEV_DEPS: ${DEBUG}
    env_file:
      - .env
    command: ["gunicorn", "api_gateway.asgi:application", "-k", "uvicorn.workers.UvicornWorker", "-b", "0.0.0.0:8000", "--workers", "4"]
    ports:
      - 8009:8000
    volumes:
      - ./:/app
    depends_on:
      - memcached
  memcached:
    container_name: ninja_portal_cache
    image: memcached:1.6.38-alpine
    command:
      - --conn-limit=1024
      - --memory-limit=16
      - --threads=4
