# Generated by Django 5.2 on 2025-04-24 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='URIPattern',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pattern', models.CharField(max_length=256, verbose_name='URI pattern')),
                ('methods', models.CharField(max_length=100, verbose_name="Allowed methods separated with comma ','")),
                ('requires_auth', models.BooleanField(default=False)),
                ('target_path', models.CharField(blank=True, default='', max_length=256, verbose_name='Target path')),
            ],
        ),
    ]
