# Generated by Django 5.2 on 2025-05-05 00:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gateway', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='uripattern',
            unique_together={('pattern', 'methods')},
        ),
    ]
