# Generated by Django 5.2 on 2025-05-07 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gateway', '0002_alter_uripattern_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='uripattern',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='Active'),
        ),
    ]
