# Generated by Django 5.2 on 2026-03-25 02:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gateway', '0003_uripattern_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='Upstream',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Name')),
                ('base_url', models.URLField(verbose_name='Base URL')),
                ('app_token', models.CharField(blank=True, default='', help_text='Token injected in the request header when redirecting to this upstream.', max_length=512, verbose_name='Application Token')),
                ('token_prefix', models.CharField(default='Bearer ', max_length=50, verbose_name='Token Prefix')),
            ],
        ),
        migrations.AddField(
            model_name='uripattern',
            name='upstream',
            field=models.ForeignKey(help_text='The destination (Upstream) to which this route will point.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='uri_patterns', to='gateway.upstream'),
        ),
    ]
